version: "3.8"

services:
  api:
    # image: "fastapi_starter:1.0.0"
    container_name: fastapi
    depends_on:
      - db
    build: ./docker/api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/usr/src/app/app:cached
      - ./db:/usr/src/app/db:cached
      - ./scripts:/usr/src/app/scripts:cached
    working_dir: /usr/src/app/scripts
    command: bash -c "./run.sh"
    networks:
      - fastapi_network
    environment:
      APP_ENV: "development"
      TZ: "Asia/Tokyo"
    env_file:
      - .env.dev
      
  db:
    # image: "fastapi_starter_db:1.0.0"
    container_name: mysql_db
    build: ./docker/db
    restart: always
    tty: true
    expose:
      - "3306"
    volumes:
      - ./docker/db/conf.d:/etc/mysql/conf.d:cached
      - ./docker/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
      - ./log/db:/var/log/mysql:cached
    networks:
      - fastapi_network
    environment:
      APP_ENV: "development"
      TZ: "Asia/Tokyo"
    env_file:
      - .env.dev

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file:
      - .env.dev
    links:
      - db
    ports:
      - "4000:80"
    volumes:
      - ./phpmyadmin/sessions:/sessions
    networks:
      - fastapi_network

networks:
  default:
    external:
      name: bridge
  fastapi_network:
    name: fastapi_network
    driver: bridge
    external: true